# Generated by Django 5.2.17 on 2026-10-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_adminaction_append_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("experience", "Experience"),
                    ("review", "Review"),
                    ("message", "Message"),
                    ("user", "User"),
                    ("booking", "Booking"),
                ],
                max_length=12,
            ),
        ),
    ]
