# Generated by Django 5.2.17 on 2026-10-06 04:03

import apps.core.fields
import apps.core.ids
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("borough", models.CharField(help_text="Alcaldía", max_length=80)),
                ("city", models.CharField(default="Ciudad de México", max_length=80)),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper("name"),
                            name="gin_trgm_ops",
                        ),
                        name="area_name_trgm",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name_es", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
                ("description_es", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "cancellation policies",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="one_default_policy",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name_es", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name used by the mobile app",
                        max_length=40,
                    ),
                ),
                ("cover_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("changes_requested", "Changes Requested"),
                            ("live", "Live"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=90)),
                ("what_you_learn", models.TextField(blank=True, max_length=3000)),
                ("who_its_for", models.TextField(blank=True, max_length=1500)),
                ("instruction_language", models.CharField(default="es", max_length=5)),
                (
                    "modality",
                    models.CharField(
                        choices=[("in_person", "In Person"), ("online", "Online")],
                        default="in_person",
                        max_length=10,
                    ),
                ),
                (
                    "offering_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("course", "Course"),
                            ("dropin", "Dropin"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                (
                    "listed_price_cents",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Per seat. Whole course if course."
                    ),
                ),
                ("default_capacity", models.PositiveIntegerField(default=10)),
                (
                    "online_url",
                    apps.core.fields.EncryptedTextField(
                        blank=True, editable=True, null=True
                    ),
                ),
                (
                    "publish_until",
                    models.DateTimeField(
                        blank=True, help_text="Empty = indefinite", null=True
                    ),
                ),
                (
                    "requires_approval_below",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Learners with a conduct score below this need provider approval",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "point_public",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("next_session_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_session_seats_left",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "rating_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                (
                    "cancellation_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.cancellationpolicy",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiences",
                        to="catalog.category",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiences",
                        to="accounts.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("capacity", models.PositiveIntegerField()),
                ("seats_booked", models.PositiveIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="catalog.experience",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("initial", "Initial"), ("edit", "Edit")],
                        max_length=10,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes Requested"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("reason_code", models.CharField(blank=True, max_length=40)),
                ("reviewer_note", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="catalog.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("declared_bytes", models.PositiveBigIntegerField()),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_upload", "Pending Upload"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_upload",
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=80)),
                ("variants", models.JSONField(blank=True, default=dict)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_s", models.FloatField(blank=True, null=True)),
                (
                    "dominant_color",
                    models.CharField(
                        blank=True,
                        help_text="#rrggbb placeholder while loading",
                        max_length=7,
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExperienceMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.experience",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="experience",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                through="catalog.ExperienceMedia",
                to="catalog.mediaasset",
            ),
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_role",
                    models.CharField(
                        choices=[
                            ("provider", "Provider"),
                            ("space_host", "Space Host"),
                        ],
                        default="provider",
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("about", models.TextField(blank=True, max_length=2000)),
                (
                    "address_line",
                    apps.core.fields.EncryptedTextField(
                        editable=True,
                        help_text="Exact address. Revealed only after booking.",
                    ),
                ),
                (
                    "address_reference",
                    apps.core.fields.EncryptedTextField(
                        blank=True,
                        editable=True,
                        help_text="Floor, door, how to get in",
                        null=True,
                    ),
                ),
                ("neighborhood", models.CharField(max_length=120)),
                ("city", models.CharField(default="Ciudad de México", max_length=80)),
                (
                    "point_exact",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "point_public",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="unverified",
                        max_length=12,
                    ),
                ),
                (
                    "is_rentable",
                    models.BooleanField(
                        default=False, help_text="Phase 4: listed for rent to providers"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spaces",
                        to="catalog.area",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "local_dow",
                    models.PositiveSmallIntegerField(help_text="ISO weekday, 1=Monday"),
                ),
                ("local_start_time", models.TimeField()),
                ("local_end_time", models.TimeField()),
                ("capacity", models.PositiveIntegerField()),
                ("seats_booked", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="catalog.cohort",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="catalog.experience",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="catalog.space",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.AddField(
            model_name="experience",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="experiences",
                to="catalog.space",
            ),
        ),
        migrations.CreateModel(
            name="SpaceMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.mediaasset",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.space"
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="space",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                through="catalog.SpaceMedia",
                to="catalog.mediaasset",
            ),
        ),
        migrations.CreateModel(
            name="CancellationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("learner_cancel", "Learner Cancel"),
                            ("no_show", "No Show"),
                        ],
                        default="learner_cancel",
                        max_length=16,
                    ),
                ),
                (
                    "min_hours_before",
                    models.PositiveIntegerField(default=0, help_text="Inclusive"),
                ),
                (
                    "max_hours_before",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Exclusive. Empty = no upper bound",
                        null=True,
                    ),
                ),
                (
                    "listed_refund_pct",
                    models.PositiveSmallIntegerField(
                        help_text="0-100, applied to the listed price"
                    ),
                ),
                (
                    "refund_fee",
                    models.BooleanField(
                        default=False, help_text="Also refund the service fee"
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="catalog.cancellationpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["policy", "applies_to", "-min_hours_before"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("listed_refund_pct__lte", 100)),
                        name="refund_pct_lte_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_hours_before__isnull", True),
                            ("max_hours_before__gt", models.F("min_hours_before")),
                            _connector="OR",
                        ),
                        name="rule_window_valid",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.CheckConstraint(
                condition=models.Q(("seats_booked__lte", models.F("capacity"))),
                name="cohort_not_overbooked",
            ),
        ),
        migrations.AddConstraint(
            model_name="experiencerevision",
            constraint=models.UniqueConstraint(
                fields=("experience", "number"), name="uniq_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="experiencerevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("review_status__in", ["draft", "pending"])),
                fields=("experience",),
                name="one_open_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="experiencemedia",
            constraint=models.UniqueConstraint(
                fields=("experience", "media"), name="uniq_experience_media"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["experience", "starts_at"], name="session_exp_start"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["local_dow", "local_start_time"], name="session_dow_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="session_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("seats_booked__lte", models.F("capacity"))),
                name="session_not_overbooked",
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                condition=models.Q(("status", "live")),
                fields=["status", "next_session_at"],
                name="exp_status_next",
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["category", "status"], name="exp_category_status"
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("title"), name="gin_trgm_ops"
                ),
                name="exp_title_trgm",
            ),
        ),
        migrations.AddConstraint(
            model_name="spacemedia",
            constraint=models.UniqueConstraint(
                fields=("space", "media"), name="uniq_space_media"
            ),
        ),
    ]
