# Generated by Django 5.2.17 on 2026-10-06 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="interest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="providerverification",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="providerverification",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="providerverification",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifications",
                to="accounts.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.mediaasset",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("phone_e164",), name="uniq_user_phone"
            ),
        ),
        migrations.AddConstraint(
            model_name="authidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "subject"), name="uniq_identity"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["user", "purpose"], name="accounts_co_user_id_f89041_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="interest",
            constraint=models.UniqueConstraint(
                fields=("user", "category"), name="uniq_interest"
            ),
        ),
        migrations.AddIndex(
            model_name="otpchallenge",
            index=models.Index(
                fields=["destination", "created_at"],
                name="accounts_ot_destina_8f5126_idx",
            ),
        ),
    ]
