# Generated by Django 5.2.17 on 2026-10-06 13:43

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_admintotpdevice"),
        ("booking", "0001_initial"),
        ("payments", "0002_initial_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderTaxProfile",
            fields=[
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tax_profile",
                        serialize=False,
                        to="accounts.providerprofile",
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("fisica", "Persona física"),
                            ("moral", "Persona moral"),
                        ],
                        default="fisica",
                        max_length=6,
                    ),
                ),
                ("rfc", models.CharField(max_length=13)),
                ("legal_name", models.CharField(max_length=200)),
                (
                    "tax_regime",
                    models.CharField(
                        blank=True,
                        help_text="SAT régimen fiscal code, e.g. 626 RESICO",
                        max_length=10,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=5)),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set by admin after checking the constancia",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WithholdingConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "isr_bps",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ISR withheld from personas físicas, basis points",
                    ),
                ),
                (
                    "iva_bps",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="IVA withheld, basis points of the IVA-inclusive amount",
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gateway", models.CharField(max_length=20)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("charge_id", models.CharField(blank=True, max_length=255)),
                ("amount_cents", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="MXN", max_length=3)),
                ("capture_manual", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_payment", "Requires Payment"),
                            ("authorized", "Authorized"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("disputed", "Disputed"),
                        ],
                        default="requires_payment",
                        max_length=20,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=30)),
                ("refunded_cents", models.PositiveBigIntegerField(default=0)),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="booking.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gateway", models.CharField(max_length=20)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("restricted", "Restricted"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("charges_enabled", models.BooleanField(default=False)),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("requirements_due", models.JSONField(blank=True, default=list)),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_account",
                        to="accounts.providerprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gateway", models.CharField(max_length=20)),
                ("external_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("listed_refund_cents", models.PositiveBigIntegerField()),
                ("fee_refund_cents", models.PositiveBigIntegerField()),
                ("total_refund_cents", models.PositiveBigIntegerField()),
                ("reason", models.CharField(max_length=40)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=80, unique=True)),
                (
                    "cancellation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="booking.cancellation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gross_cents",
                    models.BigIntegerField(
                        default=0,
                        help_text="Listed price kept by the provider after refunds",
                    ),
                ),
                ("isr_withheld_cents", models.BigIntegerField(default=0)),
                ("iva_withheld_cents", models.BigIntegerField(default=0)),
                ("net_cents", models.BigIntegerField(default=0)),
                ("isr_bps", models.PositiveIntegerField(default=0)),
                ("iva_bps", models.PositiveIntegerField(default=0)),
                ("release_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("on_hold", "On Hold"),
                            ("sent", "Sent"),
                            ("canceled", "Canceled"),
                            ("reversed", "Reversed"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_cents", models.BigIntegerField(default=0)),
                ("hold_reason", models.CharField(blank=True, max_length=80)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer",
                        to="booking.booking",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="accounts.providerprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gateway", models.CharField(max_length=20)),
                ("event_id", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=80)),
                ("payload", models.JSONField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gateway", "event_id"), name="uniq_webhook_event"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("refunded_cents__lte", models.F("amount_cents"))),
                name="refund_lte_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentcustomer",
            constraint=models.UniqueConstraint(
                fields=("user", "gateway"), name="uniq_customer_per_gateway"
            ),
        ),
    ]
