# Generated by Django 5.2.17 on 2026-10-08 23:34

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_store_channel_and_credits"),
        ("payments", "0004_fee_ten_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="surcharge_refund_cents",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CreditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_cents", models.BigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("refund", "Refund"),
                            ("spend", "Spend"),
                            ("restore", "Restore"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=12,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_entries",
                        to="booking.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_entry",
                        to="payments.refund",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="payments_cr_user_id_60893e_idx",
                    )
                ],
            },
        ),
    ]
