# Generated by Django 5.2.17 on 2026-10-06 13:43

import apps.core.ids
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_reference_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("seats", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("pending_approval", "Pending Approval"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("payment_failed", "Payment Failed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("listed_cents", models.PositiveBigIntegerField()),
                ("fee_cents", models.PositiveBigIntegerField()),
                ("total_cents", models.PositiveBigIntegerField()),
                ("fee_bps_snapshot", models.PositiveIntegerField()),
                ("policy_snapshot", models.JSONField()),
                (
                    "starts_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="First session start (copied for queries and reminders)",
                    ),
                ),
                ("ends_at", models.DateTimeField(help_text="Last session end")),
                (
                    "seats_counted",
                    models.BooleanField(
                        default=False,
                        help_text="True while this booking occupies inventory",
                    ),
                ),
                ("approval_deadline", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_window_closes_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.cohort",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.experience",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="catalog.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor_role",
                    models.CharField(
                        choices=[
                            ("learner", "Learner"),
                            ("provider", "Provider"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "hours_before_start",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "rule_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="The policy rule that produced the refund",
                    ),
                ),
                ("listed_refund_cents", models.PositiveBigIntegerField()),
                ("fee_refund_cents", models.PositiveBigIntegerField()),
                ("refund_cents", models.PositiveBigIntegerField()),
                ("reason_code", models.CharField(blank=True, max_length=40)),
                ("note", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellations",
                        to="booking.booking",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeatHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seats", models.PositiveSmallIntegerField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("converted", "Converted"),
                            ("expired", "Expired"),
                            ("released", "Released"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="catalog.cohort",
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.experience",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="catalog.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="hold",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="booking.seathold",
            ),
        ),
        migrations.CreateModel(
            name="BookingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("present", "Present"),
                            ("absent", "Absent"),
                        ],
                        default="unknown",
                        max_length=8,
                    ),
                ),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_sessions",
                        to="booking.booking",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_sessions",
                        to="catalog.session",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "session"), name="uniq_booking_session"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="seathold",
            index=models.Index(
                fields=["session", "status", "expires_at"],
                name="booking_sea_session_fb94d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="seathold",
            index=models.Index(
                fields=["cohort", "status", "expires_at"],
                name="booking_sea_cohort__2a8bc0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="seathold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cohort__isnull", True), ("session__isnull", False)),
                    models.Q(("cohort__isnull", False), ("session__isnull", True)),
                    _connector="OR",
                ),
                name="hold_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["learner", "starts_at"], name="booking_boo_learner_e46dc4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_cents",
                        django.db.models.expressions.CombinedExpression(
                            models.F("listed_cents"), "+", models.F("fee_cents")
                        ),
                    )
                ),
                name="booking_total_consistent",
            ),
        ),
    ]
