# Generated by Django 5.2.17 on 2026-10-08 23:34

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        ("catalog", "0002_reference_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="booking_total_consistent",
        ),
        migrations.AddField(
            model_name="booking",
            name="channel",
            field=models.CharField(
                default="card",
                help_text="card: Stripe (or credits); app_store: Apple in-app purchase",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="store_surcharge_cents",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Extra charged on the App Store price to cover Apple's commission and VAT. Not refundable on learner cancellation.",
            ),
        ),
        migrations.AddField(
            model_name="seathold",
            name="channel",
            field=models.CharField(
                default="card",
                help_text="card | app_store (decided by device and experience)",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_cents",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("listed_cents"), "+", models.F("fee_cents")
                            ),
                            "+",
                            models.F("store_surcharge_cents"),
                        ),
                    )
                ),
                name="booking_total_consistent",
            ),
        ),
    ]
